### ISSUE TITLE
Fails to run in Ubuntu 18.04

### ISSUE THREAD

**Issue by madprops** [cjbassi/ytop#33] opened 2020-01-29 03:32 UTC
ytop 0.4.0

Moved it to /bin and when executed I get:

```
The application panicked (crashed).
  called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "failed to use statvfs: statvfs return an error code" }
in src/libcore/result.rs, line 1165
```

**Comment by cjbassi** [comment] 2020-01-29 15:54
Do you have a partition that has a space in the mount point? If so, this is probably a duplicate of #29.

**Comment by madprops** [comment] 2020-01-30 06:33
I do actually, like: `/media/yo/Storage 1/`

**Comment by cjbassi** [comment] 2020-01-30 14:36
Cool, I'm just going to go ahead and close this as a duplicate then.

**Closed as completed by cjbassi** 2020-01-30 14:36 UTC
Labels: bug, duplicate
